name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build-test-publishArtifacts:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Build with Maven
          run: mvn clean install
        
        - name: Unit test case
          run: mvn test
      
        - name: Generate and Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: prodProjectArtifact
            path: target/*.war 

        - name: Cache Maven dependencies
          uses: actions/cache@v2
          with:
            path: |
              ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        
        - name: Build Docker image
          run: |
            docker build -t prodproject:latest .
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push Docker image to registry
          run: |
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker push "${DOCKER_USERNAME}/prodproject:latest"
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            
          
  
    
        # - name: Run SonarCloud analysis
        #   run: mvn org.sonarsource.scanner.maven:sonar
    
        # - name: Run SonarCloud Analysis
        #   uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}  # Needed to get PR information
        #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        #   with:
        #    args:
        #     -Dsonar.projectKey= devProject_CI-CD
        #     -Dsonar.organization= rashika3031
    
